In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Cleaning mvps data

In [2]:
mvps = pd.read_csv("mvps.csv" , index_col = 0)

In [3]:
mvps.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [4]:
mvps.columns

Index(['Rank', 'Player', 'Age', 'Tm', 'First', 'Pts Won', 'Pts Max', 'Share',
       'G', 'MP', 'PTS', 'TRB', 'AST', 'STL', 'BLK', 'FG%', '3P%', 'FT%', 'WS',
       'WS/48', 'Year'],
      dtype='object')

In [5]:
mvps = mvps[["Player" , "Year" , "Pts Won", "Pts Max", "Share"]]

In [6]:
mvps.head()

            Player  Year  Pts Won  Pts Max  Share
0   Michael Jordan  1991    891.0      960  0.928
1    Magic Johnson  1991    497.0      960  0.518
2   David Robinson  1991    476.0      960  0.496
3  Charles Barkley  1991    222.0      960  0.231
4      Karl Malone  1991    142.0      960  0.148

## Cleaning Players Data

In [7]:
players = pd.read_csv("players.csv" , index_col = 0)

In [8]:
players.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [9]:
players = players.drop(labels = ["Rk"] , axis = 1)
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [10]:
# Removing asteriks in Players name

players["Player"].head(30) 

# As we can see at index no . : 23  Charles Barkley* is there
# but in mvps' DF, Player column doesnot have asterik symbol
# so we need to remove the asterik symbol.

0         Alaa Abdelnaby
1     Mahmoud Abdul-Rauf
2             Mark Acres
3          Michael Adams
4           Mark Aguirre
5            Danny Ainge
6            Mark Alarie
7           Steve Alford
8          Greg Anderson
9          Greg Anderson
10         Greg Anderson
11         Greg Anderson
12         Nick Anderson
13          Ron Anderson
14       Willie Anderson
15        Michael Ansley
16        B.J. Armstrong
17         Vincent Askew
18          Keith Askins
19           Miloš Babić
20          Thurl Bailey
21           Cedric Ball
22         Ken Bannister
23      Charles Barkley*
24           Dana Barros
25           John Battle
26          Kenny Battle
27          Kenny Battle
28          Kenny Battle
29       William Bedford
Name: Player, dtype: object

In [11]:
players['Player'] = players['Player'].str.replace("*" , "" , regex = False)

In [12]:
players['Player'].head(30)

0         Alaa Abdelnaby
1     Mahmoud Abdul-Rauf
2             Mark Acres
3          Michael Adams
4           Mark Aguirre
5            Danny Ainge
6            Mark Alarie
7           Steve Alford
8          Greg Anderson
9          Greg Anderson
10         Greg Anderson
11         Greg Anderson
12         Nick Anderson
13          Ron Anderson
14       Willie Anderson
15        Michael Ansley
16        B.J. Armstrong
17         Vincent Askew
18          Keith Askins
19           Miloš Babić
20          Thurl Bailey
21           Cedric Ball
22         Ken Bannister
23       Charles Barkley
24           Dana Barros
25           John Battle
26          Kenny Battle
27          Kenny Battle
28          Kenny Battle
29       William Bedford
Name: Player, dtype: object

In [13]:
# Removing the repetitions of row for a player in a year
# Player : Greg Anderson

players.head(30)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
5,Danny Ainge,SG,31,POR,80,0,21.4,4.2,8.9,.472,...,0.6,2.0,2.6,3.6,0.8,0.2,1.3,2.4,11.1,1991
6,Mark Alarie,PF,27,WSB,42,1,14.0,2.4,5.4,.440,...,1.0,1.8,2.8,1.1,0.4,0.2,1.0,2.1,5.8,1991
7,Steve Alford,PG,26,DAL,34,0,6.9,1.7,3.4,.504,...,0.3,0.4,0.7,0.6,0.2,0.0,0.5,0.3,4.4,1991
8,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,2.8,.370,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,4.0,1.000,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,4.7,.440,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991
12,Nick Anderson,SG,23,ORL,70,42,28.2,5.7,12.2,.467,...,1.3,4.2,5.5,1.5,1.1,0.6,1.6,2.1,14.1,1991
13,Ron Anderson,SF,32,PHI,82,13,28.5,6.2,12.9,.485,...,1.3,3.2,4.5,1.4,0.8,0.2,1.2,2.0,14.6,1991
14,Willie Anderson,SG,24,SAS,75,75,34.6,6.0,13.2,.457,...,0.9,3.8,4.7,4.8,1.1,0.6,2.2,3.0,14.4,1991
15,Michael Ansley,SF,23,ORL,67,1,13.1,2.1,3.9,.548,...,1.8,2.0,3.8,0.4,0.4,0.1,0.5,1.9,5.7,1991
16,B.J. Armstrong,PG,23,CHI,82,0,21.1,3.7,7.7,.481,...,0.3,1.5,1.8,3.7,0.9,0.0,1.3,1.4,8.8,1991
17,Vincent Askew,SG,24,GSW,7,0,12.1,1.7,3.6,.480,...,1.0,0.6,1.6,1.9,0.3,0.0,0.9,3.0,4.7,1991
18,Keith Askins,SF,23,MIA,39,1,6.8,0.9,2.1,.420,...,0.8,1.0,1.7,0.5,0.4,0.3,0.3,1.2,2.2,1991
19,Miloš Babić,PF,22,CLE,12,0,4.3,0.5,1.6,.316,...,0.5,0.3,0.8,0.3,0.1,0.1,0.4,0.6,1.6,1991
20,Thurl Bailey,PF,29,UTA,82,22,30.3,4.9,10.6,.458,...,1.2,3.7,5.0,1.5,0.6,1.1,1.6,2.0,12.4,1991
21,Cedric Ball,PF,22,LAC,7,0,3.7,0.4,1.1,.375,...,0.7,0.9,1.6,0.0,0.0,0.3,0.3,0.7,1.1,1991
22,Ken Bannister,PF,30,LAC,47,3,7.2,0.9,1.7,.531,...,0.7,1.3,2.0,0.2,0.1,0.1,0.5,1.6,2.4,1991
23,Charles Barkley,SF,27,PHI,67,67,37.3,9.9,17.4,.570,...,3.9,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,1991
24,Dana Barros,PG,23,SEA,66,0,11.4,2.3,4.7,.495,...,0.3,0.8,1.1,1.7,0.3,0.0,0.8,0.6,6.3,1991
25,John Battle,SG,28,ATL,79,2,23.6,5.0,10.9,.461,...,0.4,1.6,2.0,2.7,0.6,0.1,1.4,1.8,13.6,1991
26,Kenny Battle,SG,26,TOT,56,8,16.9,2.4,5.0,.472,...,1.5,1.7,3.1,1.1,1.1,0.3,0.9,1.9,6.1,1991
27,Kenny Battle,SG,26,PHO,16,4,16.4,2.4,5.4,.442,...,1.3,2.0,3.3,0.9,1.2,0.4,1.1,1.6,6.0,1991
28,Kenny Battle,SG,26,DEN,40,4,17.1,2.4,4.9,.485,...,1.6,1.5,3.1,1.2,1.0,0.3,0.9,2.1,6.1,1991
29,William Bedford,C,27,DET,60,4,9.4,1.8,4.0,.438,...,0.9,1.3,2.2,0.5,0.0,0.6,0.5,1.3,4.5,1991

In [14]:
players.groupby(["Player","Year"]).get_group(("Greg Anderson" , 1991))
# So four rows are there corresponding to year 1991 because he has played for four teams that year.

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,2.8,.370,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,4.0,1.000,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,4.7,.440,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991

In [15]:
players.groupby(["Player","Year"]).get_group(("Greg Anderson" , 1992))

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992

In [16]:
# custom function
def single_row(df):
    
    if df.shape[0] == 1:
        return df
    else:
        
        row = df[df["Tm"] == "TOT"]
        row['Tm'] = df.iloc[-1,:]["Tm"]
        
        return row

In [17]:
players = players.groupby(["Player","Year"]).apply(single_row)

In [18]:
players.head(10)
# Hierarchical indexing

                         Player Pos Age   Tm   G  GS    MP   FG   FGA   FG%  \
Player     Year
A.C. Green 1991 164  A.C. Green  PF  27  LAL  82  21  26.4  3.1   6.6  .476
           1992 174  A.C. Green  PF  28  LAL  82  53  35.4  4.7   9.8  .476
           1993 157  A.C. Green  PF  29  LAL  82  55  34.4  4.6   8.6  .537
           1994 177  A.C. Green  PF  30  PHO  82  55  34.5  5.7  11.3  .502
           1995 165  A.C. Green  SF  31  PHO  82  52  32.8  3.8   7.5  .504
           1996 190  A.C. Green  SF  32  PHO  82  36  25.8  2.6   5.4  .484
           1997 200  A.C. Green  PF  33  DAL  83  73  30.0  2.8   5.8  .483
           1998 192  A.C. Green  PF  34  DAL  82  68  32.3  3.0   6.5  .453
           1999 183  A.C. Green  PF  35  DAL  50  35  18.5  2.2   5.1  .422
           2000 184  A.C. Green  PF  36  LAL  82  82  23.5  2.1   4.7  .447

                     ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  Year
Player     Year      ...
A.C. Green 1991 164  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4   9.1  1991
           1992 174  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7  13.6  1992
           1993 157  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8  12.8  1993
           1994 177  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7  14.7  1994
           1995 165  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8  11.2  1995
           1996 190  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0  1.7   7.5  1996
           1997 200  ...  2.7  5.2  7.9  0.8  0.8  0.2  0.9  1.7   7.2  1997
           1998 192  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8  1.9   7.3  1998
           1999 183  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4  1.4   4.9  1999
           2000 184  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6  1.5   5.0  2000

[10 rows x 30 columns]

In [19]:
# Dropping Hierarchical indexing

players.index = players.index.droplevel()
players.index = players.index.droplevel()

In [20]:
players.head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
164,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
174,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
157,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
177,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
165,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995
190,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,.484,...,2.0,4.7,6.8,0.9,0.5,0.3,1.0,1.7,7.5,1996
200,A.C. Green,PF,33,DAL,83,73,30.0,2.8,5.8,.483,...,2.7,5.2,7.9,0.8,0.8,0.2,0.9,1.7,7.2,1997
192,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,.453,...,2.7,5.5,8.1,1.5,1.0,0.3,0.8,1.9,7.3,1998
183,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,.422,...,1.6,2.9,4.6,0.5,0.6,0.2,0.4,1.4,4.9,1999
184,A.C. Green,PF,36,LAL,82,82,23.5,2.1,4.7,.447,...,2.0,4.0,5.9,1.0,0.6,0.2,0.6,1.5,5.0,2000

## Combining mvps and Players Data

In [21]:
combined = players.merge(mvps , how = "outer" , on = ["Player" , "Year"])

In [22]:
combined.head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN
5,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,.484,...,0.9,0.5,0.3,1.0,1.7,7.5,1996,NaN,NaN,NaN
6,A.C. Green,PF,33,DAL,83,73,30.0,2.8,5.8,.483,...,0.8,0.8,0.2,0.9,1.7,7.2,1997,NaN,NaN,NaN
7,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,.453,...,1.5,1.0,0.3,0.8,1.9,7.3,1998,NaN,NaN,NaN
8,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,.422,...,0.5,0.6,0.2,0.4,1.4,4.9,1999,NaN,NaN,NaN
9,A.C. Green,PF,36,LAL,82,82,23.5,2.1,4.7,.447,...,1.0,0.6,0.2,0.6,1.5,5.0,2000,NaN,NaN,NaN

In [23]:
# Fixing NaN value

combined[['Pts Won','Pts Max','Share']] = combined[['Pts Won','Pts Max','Share']].fillna(0)

In [24]:
combined.head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
5,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,.484,...,0.9,0.5,0.3,1.0,1.7,7.5,1996,0.0,0.0,0.0
6,A.C. Green,PF,33,DAL,83,73,30.0,2.8,5.8,.483,...,0.8,0.8,0.2,0.9,1.7,7.2,1997,0.0,0.0,0.0
7,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,.453,...,1.5,1.0,0.3,0.8,1.9,7.3,1998,0.0,0.0,0.0
8,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,.422,...,0.5,0.6,0.2,0.4,1.4,4.9,1999,0.0,0.0,0.0
9,A.C. Green,PF,36,LAL,82,82,23.5,2.1,4.7,.447,...,1.0,0.6,0.2,0.6,1.5,5.0,2000,0.0,0.0,0.0

## Cleaning Teams data

In [25]:
teams = pd.read_csv("team.csv" , index_col = 0)

In [26]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                   Team
0   56  26  .683     —  111.5  105.7   5.22  1991        Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991    Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991       New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991     Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991        New Jersey Nets
..  ..  ..   ...   ...    ...    ...    ...   ...                    ...
13  56  26  .683     —  115.6  109.9   5.37  2022     Memphis Grizzlies*
14  52  30  .634   4.0  108.0  104.7   3.12  2022      Dallas Mavericks*
15  36  46  .439  20.0  109.3  110.3  -0.84  2022  New Orleans Pelicans*
16  34  48  .415  22.0  113.2  113.0   0.02  2022      San Antonio Spurs
17  20  62  .244  36.0  109.7  118.2  -8.26  2022        Houston Rockets

[1068 rows x 9 columns]

In [27]:
teams.head(10)

,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*

In [28]:
#teams['Team'].nunique()

In [29]:
# Removing row with division thing

teams[~teams["W"].str.contains("Division")].head(10)

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                 Team
0   56  26  .683     —  111.5  105.7   5.22  1991      Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991  Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991     New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991   Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991      New Jersey Nets
5   24  58  .293  32.0  101.8  107.8  -5.91  1991           Miami Heat
7   61  21  .744     —  110.0  101.0   8.57  1991       Chicago Bulls*
8   50  32  .610  11.0  100.1   96.8   3.08  1991     Detroit Pistons*
9   48  34  .585  13.0  106.4  104.0   2.33  1991     Milwaukee Bucks*
10  43  39  .524  18.0  109.8  109.0   0.72  1991       Atlanta Hawks*

In [30]:
teams = teams[~teams["W"].str.contains("Division")]
teams.head(10)

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                 Team
0   56  26  .683     —  111.5  105.7   5.22  1991      Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991  Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991     New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991   Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991      New Jersey Nets
5   24  58  .293  32.0  101.8  107.8  -5.91  1991           Miami Heat
7   61  21  .744     —  110.0  101.0   8.57  1991       Chicago Bulls*
8   50  32  .610  11.0  100.1   96.8   3.08  1991     Detroit Pistons*
9   48  34  .585  13.0  106.4  104.0   2.33  1991     Milwaukee Bucks*
10  43  39  .524  18.0  109.8  109.0   0.72  1991       Atlanta Hawks*

In [31]:
# Removing "*" symbol in Team column

teams["Team"] = teams["Team"].str.replace("*" , "" , regex = False)

C:\Users\aakas\AppData\Local\Temp\ipykernel_11608\1371364167.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teams["Team"] = teams["Team"].str.replace("*" , "" , regex = False)

In [32]:
teams.head()

    W   L  W/L%    GB   PS/G   PA/G    SRS  Year                Team
0  56  26  .683     —  111.5  105.7   5.22  1991      Boston Celtics
1  44  38  .537  12.0  105.4  105.6  -0.39  1991  Philadelphia 76ers
2  39  43  .476  17.0  103.1  103.3  -0.43  1991     New York Knicks
3  30  52  .366  26.0  101.4  106.4  -4.84  1991  Washington Bullets
4  26  56  .317  30.0  102.9  107.5  -4.53  1991     New Jersey Nets

### Unique team names

In [33]:
# Unique team name in 'teams' DF
teams['Team'].unique()

array(['Boston Celtics', 'Philadelphia 76ers', 'New York Knicks',
       'Washington Bullets', 'New Jersey Nets', 'Miami Heat',
       'Chicago Bulls', 'Detroit Pistons', 'Milwaukee Bucks',
       'Atlanta Hawks', 'Indiana Pacers', 'Cleveland Cavaliers',
       'Charlotte Hornets', 'San Antonio Spurs', 'Utah Jazz',
       'Houston Rockets', 'Orlando Magic', 'Minnesota Timberwolves',
       'Dallas Mavericks', 'Denver Nuggets', 'Portland Trail Blazers',
       'Los Angeles Lakers', 'Phoenix Suns', 'Golden State Warriors',
       'Seattle SuperSonics', 'Los Angeles Clippers', 'Sacramento Kings',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [34]:
teams['Team'].nunique()

37

In [35]:
# Unique team name in 'combined' DF
# combined.columns

combined['Tm'].unique()

# So in the 'combined' DF we have abbreviation of the team name but 
# in the 'teams' DF we've full team name

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'CHI', 'GSW', 'IND',
       'WAS', 'MIN', 'BOS', 'HOU', 'DEN', 'ORL', 'NOH', 'TOR', 'SAC',
       'CHO', 'PHI', 'POR', 'DET', 'OKC', 'UTA', 'MIL', 'VAN', 'SEA',
       'NJN', 'NOK', 'LAC', 'ATL', 'CHA', 'MEM', 'NYK', 'NOP', 'BRK',
       'SAS', 'CHH'], dtype=object)

In [36]:
# So lets map the team name

names = {}

with open("Team Abbreviation.csv") as f:
    
    lines = f.readlines()
    #print(lines)
    for line in lines[1:]:
        #print(line.replace("\n" , ""))
        name ,abbr = line.replace("\n" , "").split(",")
        
        names[abbr.upper()] = name
        
print(names)

{'BOS': 'Boston Celtics', 'BRK': 'Brooklyn Nets', 'NYK': 'New York Knicks', 'PHI': 'Philadelphia 76ers', 'TOR': 'Toronto Raptors', 'GSW': 'Golden State Warriors', 'LAC': 'Los Angeles Clippers', 'LAL': 'Los Angeles Lakers', 'PHO': 'Phoenix Suns', 'SAC': 'Sacramento Kings', 'CHI': 'Chicago Bulls', 'CLE': 'Cleveland Cavaliers', 'DET': 'Detroit Pistons', 'IND': 'Indiana Pacers', 'MIL': 'Milwaukee Bucks', 'DAL': 'Dallas Mavericks', 'HOU': 'Houston Rockets', 'MEM': 'Memphis Grizzlies', 'NOH': 'New Orleans Hornets', 'SAS': 'San Antonio Spurs', 'ATL': 'Atlanta Hawks', 'CHO': 'Charlotte Bobcats', 'MIA': 'Miami Heat', 'ORL': 'Orlando Magic', 'WAS': 'Washington Wizards', 'DEN': 'Denver Nuggets', 'MIN': 'Minnesota Timberwolves', 'OKC': 'Oklahoma City Thunder', 'POR': 'Portland Trail Blazers', 'UTA': 'Utah Jazz', 'WSB': 'Washington Bulltets', 'NJN': 'New Jersey Nets', 'CHA': 'Charlotte Hornets', 'SEA': 'Seattle SuperSonics', 'VAN': 'Vancouver Grizzlies', 'NOK': 'New Orleans/Oklahoma City Hornets', 'NOP': 'New Orleans Pelicans', 'CHH': 'Charlotte Hornets'}

In [37]:
combined['Tm'].map(names)

0          Los Angeles Lakers
1          Los Angeles Lakers
2          Los Angeles Lakers
3                Phoenix Suns
4                Phoenix Suns
                 ...
14692         Detroit Pistons
14693         Detroit Pistons
14694           Atlanta Hawks
14695    Los Angeles Clippers
14696    Los Angeles Clippers
Name: Tm, Length: 14697, dtype: object

In [38]:
combined['Team'] = combined['Tm'].map(names)

In [39]:
combined.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0,Phoenix Suns

## Combining Team and combined DF

In [40]:
stats = combined.merge(teams , how="outer" , on = ["Team" , "Year"])

In [41]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Charlotte Hornets,36,46,.439,8.0,108.2,108.0,0.07
14718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Charlotte Hornets,39,43,.476,3.0,110.7,111.8,-1.32
14719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Charlotte Hornets,23,42,.354,17.0,102.9,109.6,-7.03
14720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Charlotte Hornets,33,39,.458,8.0,109.5,111.4,-1.94
14721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Charlotte Hornets,43,39,.524,10.0,115.3,114.9,0.53

In [42]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0,Phoenix Suns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0,Detroit Pistons
14693,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0,Detroit Pistons
14694,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0,Atlanta Hawks
14695,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0,Los Angeles Clippers
14696,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0,Los Angeles Clippers

In [43]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0   56  26  .683     —  111.5  105.7   5.22  1991        Boston Celtics
1   44  38  .537  12.0  105.4  105.6  -0.39  1991    Philadelphia 76ers
2   39  43  .476  17.0  103.1  103.3  -0.43  1991       New York Knicks
3   30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
..  ..  ..   ...   ...    ...    ...    ...   ...                   ...
13  56  26  .683     —  115.6  109.9   5.37  2022     Memphis Grizzlies
14  52  30  .634   4.0  108.0  104.7   3.12  2022      Dallas Mavericks
15  36  46  .439  20.0  109.3  110.3  -0.84  2022  New Orleans Pelicans
16  34  48  .415  22.0  113.2  113.0   0.02  2022     San Antonio Spurs
17  20  62  .244  36.0  109.7  118.2  -8.26  2022       Houston Rockets

[936 rows x 9 columns]

In [44]:
stats = stats[~stats["Player"].isna()]

In [45]:
stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14697 entries, 0 to 14696
Data columns (total 41 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player   14697 non-null  object
 1   Pos      14697 non-null  object
 2   Age      14697 non-null  object
 3   Tm       14697 non-null  object
 4   G        14697 non-null  object
 5   GS       14697 non-null  object
 6   MP       14697 non-null  object
 7   FG       14697 non-null  object
 8   FGA      14697 non-null  object
 9   FG%      14638 non-null  object
 10  3P       14697 non-null  object
 11  3PA      14697 non-null  object
 12  3P%      12611 non-null  object
 13  2P       14697 non-null  object
 14  2PA      14697 non-null  object
 15  2P%      14597 non-null  object
 16  eFG%     14638 non-null  object
 17  FT       14697 non-null  object
 18  FTA      14697 non-null  object
 19  FT%      14176 non-null  object
 20  ORB      14697 non-null  object
 21  DRB      14697 non-null  object
 22  TRB      14697 non-null  object
 23  AST      14697 non-null  object
 24  STL      14697 non-null  object
 25  BLK      14697 non-null  object
 26  TOV      14697 non-null  object
 27  PF       14697 non-null  object
 28  PTS      14697 non-null  object
 29  Year     14697 non-null  int64
 30  Pts Won  14697 non-null  float64
 31  Pts Max  14697 non-null  float64
 32  Share    14697 non-null  float64
 33  Team     14697 non-null  object
 34  W        14296 non-null  object
 35  L        14296 non-null  object
 36  W/L%     14296 non-null  object
 37  GB       14296 non-null  object
 38  PS/G     14296 non-null  object
 39  PA/G     14296 non-null  object
 40  SRS      14296 non-null  object
dtypes: float64(3), int64(1), object(37)
memory usage: 4.7+ MB

## Converting the dtypes of the columns

In [46]:
stats = stats.apply(pd.to_numeric , errors = "ignore" )

In [47]:
stats.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [48]:
stats["GB"].unique()

array(['5.0', '14.0', '23.0', '7.0', '—', '40.0', '42.0', '18.0', '6.0',
       '24.0', nan, '37.0', '29.0', '21.0', '28.0', '25.0', '8.0', '19.0',
       '1.0', '13.0', '17.0', '3.0', '15.0', '9.0', '2.0', '35.0', '20.0',
       '11.0', '26.0', '16.0', '41.0', '12.0', '50.0', '10.0', '30.0',
       '34.0', '4.0', '1.5', '22.0', '51.0', '36.0', '43.0', '39.0',
       '18.5', '31.0', '48.0', '46.0', '10.5', '32.0', '38.0', '33.0',
       '27.0', '21.5', '45.0', '22.5', '25.5', '3.5', '20.5', '11.5',
       '44.0', '52.0', '56.0', '2.5', '12.5', '47.0', '32.5', '4.5'],
      dtype=object)

In [49]:
stats["GB"] = stats["GB"].str.replace("—" , "0" , regex = False)

In [50]:
stats["GB"].unique()

array(['5.0', '14.0', '23.0', '7.0', '0', '40.0', '42.0', '18.0', '6.0',
       '24.0', nan, '37.0', '29.0', '21.0', '28.0', '25.0', '8.0', '19.0',
       '1.0', '13.0', '17.0', '3.0', '15.0', '9.0', '2.0', '35.0', '20.0',
       '11.0', '26.0', '16.0', '41.0', '12.0', '50.0', '10.0', '30.0',
       '34.0', '4.0', '1.5', '22.0', '51.0', '36.0', '43.0', '39.0',
       '18.5', '31.0', '48.0', '46.0', '10.5', '32.0', '38.0', '33.0',
       '27.0', '21.5', '45.0', '22.5', '25.5', '3.5', '20.5', '11.5',
       '44.0', '52.0', '56.0', '2.5', '12.5', '47.0', '32.5', '4.5'],
      dtype=object)

In [51]:
stats = stats.apply(pd.to_numeric , errors = "ignore")

In [52]:
stats.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

### Highest scoring individual in each season

In [54]:
stats.groupby("Year").apply(lambda x : x.sort_values("PTS" , ascending = False).head(1) )

,,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
Year,,,,,,,,,,,,,,,,,,,,,,
1991,10358,Michael Jordan,SG,27,CHI,82,82,37.0,12.1,22.4,0.539,...,960.0,0.928,Chicago Bulls,61.0,21.0,0.744,0.0,110.0,101.0,8.57
1992,10371,Michael Jordan,SG,28,CHI,80,80,38.8,11.8,22.7,0.519,...,960.0,0.938,Chicago Bulls,67.0,15.0,0.817,0.0,109.9,99.5,10.07
1993,10384,Michael Jordan,SG,29,CHI,78,78,39.3,12.7,25.7,0.495,...,980.0,0.577,Chicago Bulls,57.0,25.0,0.695,0.0,105.2,98.9,6.19
1994,9078,David Robinson,C,28,SAS,80,80,40.5,10.5,20.7,0.507,...,1010.0,0.723,San Antonio Spurs,55.0,27.0,0.671,3.0,100.0,94.8,5.05
1995,7643,Shaquille O'Neal,C,22,ORL,79,79,37.0,11.8,20.2,0.583,...,1050.0,0.576,Orlando Magic,57.0,25.0,0.695,0.0,110.9,103.8,6.44
1996,10962,Michael Jordan,SG,32,CHI,82,82,37.7,11.2,22.6,0.495,...,1130.0,0.986,Chicago Bulls,72.0,10.0,0.878,0.0,105.2,92.9,11.80
1997,10976,Michael Jordan,SG,33,CHI,82,82,37.9,11.2,23.1,0.486,...,1150.0,0.832,Chicago Bulls,69.0,13.0,0.841,0.0,103.1,92.3,10.70
1998,10990,Michael Jordan,SG,34,CHI,82,82,38.8,10.7,23.1,0.465,...,1160.0,0.934,Chicago Bulls,62.0,20.0,0.756,0.0,96.7,89.6,7.24
1999,999,Allen Iverson,SG,23,PHI,48,48,41.5,9.1,22.0,0.412,...,1180.0,0.270,Philadelphia 76ers,28.0,22.0,0.560,5.0,89.7,87.6,2.56
2000,143,Shaquille O'Neal,C,27,LAL,79,79,40.0,12.1,21.1,0.574,...,1210.0,0.998,Los Angeles Lakers,67.0,15.0,0.817,0.0,100.8,92.3,8.41
2001,1030,Allen Iverson,SG,25,PHI,71,71,42.0,10.7,25.5,0.420,...,1240.0,0.904,Philadelphia 76ers,56.0,26.0,0.683,0.0,94.7,90.4,3.64
2002,1046,Allen Iverson,SG,26,PHI,60,59,43.7,11.1,27.8,0.398,...,1260.0,0.023,Philadelphia 76ers,43.0,39.0,0.524,9.0,91.0,89.4,1.27
2003,7166,Tracy McGrady,SG,23,ORL,75,74,39.4,11.1,24.2,0.457,...,1190.0,0.359,Orlando Magic,42.0,40.0,0.512,7.0,98.5,98.4,-0.39
2004,7179,Tracy McGrady,SG,24,ORL,67,67,39.9,9.7,23.4,0.417,...,0.0,0.000,Orlando Magic,21.0,61.0,0.256,26.0,94.0,101.1,-7.25
2005,1093,Allen Iverson,PG,29,PHI,75,75,42.3,10.3,24.2,0.424,...,1270.0,0.189,Philadelphia 76ers,43.0,39.0,0.524,2.0,99.1,99.9,-1.07
2006,1113,Kobe Bryant,SG,27,LAL,80,80,41.0,12.2,27.2,0.450,...,1250.0,0.386,Los Angeles Lakers,45.0,37.0,0.549,9.0,99.4,96.9,2.53
2007,1127,Kobe Bryant,SG,28,LAL,77,77,40.8,10.6,22.8,0.463,...,1290.0,0.404,Los Angeles Lakers,42.0,40.0,0.512,19.0,103.3,103.4,0.24
2008,5775,LeBron James,SF,23,CLE,75,74,40.4,10.6,21.9,0.484,...,1260.0,0.348,Cleveland Cavaliers,45.0,37.0,0.549,14.0,96.4,96.7,-0.53
2009,13803,Dwyane Wade,SG,27,MIA,79,79,38.6,10.8,22.0,0.491,...,1210.0,0.562,Miami Heat,43.0,39.0,0.524,16.0,98.3,98.0,0.49
2010,9229,Kevin Durant,SF,21,OKC,82,82,39.5,9.7,20.3,0.476,...,1230.0,0.495,Oklahoma City Thunder,50.0,32.0,0.610,3.0,101.5,98.0,3.55
2011,13133,Kevin Durant,SF,22,OKC,78,78,38.9,9.1,19.7,0.462,...,1210.0,0.157,Oklahoma City Thunder,55.0,27.0,0.671,0.0,104.8,101.0,3.81
2012,14018,Kevin Durant,SF,23,OKC,66,66,38.6,9.7,19.7,0.496,...,1210.0,0.735,Oklahoma City Thunder,47.0,19.0,0.712,0.0,103.1,96.9,6.44
2013,5501,Carmelo Anthony,PF,28,NYK,67,67,37.0,10.0,22.2,0.449,...,1210.0,0.393,New York Knicks,54.0,28.0,0.659,0.0,100.0,95.7,3.73
2014,6595,Kevin Durant,SF,25,OKC,81,81,38.5,10.5,20.8,0.503,...,1250.0,0.986,Oklahoma City Thunder,59.0,23.0,0.720,0.0,106.2,99.8,6.66
2015,6618,Russell Westbrook,PG,26,OKC,67,67,34.4,9.4,22.0,0.426,...,1300.0,0.271,Oklahoma City Thunder,45.0,37.0,0.549,6.0,104.0,101.8,2.47
2016,5824,Stephen Curry,PG,27,GSW,79,79,34.2,10.2,20.2,0.504,...,1310.0,1.000,Golden State Warriors,73.0,9.0,0.890,0.0,114.9,104.1,10.38
2017,6647,Russell Westbrook,PG,28,OKC,81,81,34.6,10.2,24.0,0.425,...,1010.0,0.879,Oklahoma City Thunder,47.0,35.0,0.573,4.0,106.6,105.8,1.14
2018,929,James Harden,SG,28,HOU,72,72,35.4,9.0,20.1,0.449,...,1010.0,0.955,Houston Rockets,65.0,17.0,0.793,0.0,112.4,103.9,8.21
2019,10065,James Harden,PG,29,HOU,78,78,36.8,10.8,24.5,0.442,...,1010.0,0.768,Houston Rockets,53.0,29.0,0.646,0.0,113.9,109.1,4.96
2020,10082,James Harden,SG,30,HOU,68,68,36.5,9.9,22.3,0.444,...,1010.0,0.363,Houston Rockets,44.0,28.0,0.611,0.0,117.8,114.8,3.13
2021,3843,Stephen Curry,PG,32,GSW,63,63,34.2,10.4,21.7,0.482,...,1010.0,0.449,Golden State Warriors,39.0,33.0,0.542,12.0,113.7,112.7,1.10
2022,837,Joel Embiid,C,27,PHI,68,68,33.8,9.8,19.6,0.499,...,1000.0,0.706,Philadelphia 76ers,51.0,31.0,0.622,0.0,109.9,107.3,2.57

## Exporting the DF

In [53]:
stats.to_csv("mvps_player_team.csv")